CREATE TABLE Orders (
    Order_Id int NOT NULL PRIMARY KEY IDENTITY(1,1),
    Customer_Id int NOT NULL FOREIGN KEY REFERENCES Customer(Customer_Id),
    Company_Id int NOT NULL FOREIGN KEY REFERENCES Company(Company_Id),
    Product_Id int NOT NULL FOREIGN KEY REFERENCES Product(Product_Id),
	Order_Quantity int,
	Order_Price int,
	Order_Status_Id int NOT NULL FOREIGN KEY REFERENCES OrderStatus(OrderStaus_Id),
);
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (1,10,14,5,3505,3)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (77,5,18,3,2700,3)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (31,1,2,2,214,3)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (60,2,17,5,2530,3)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (39,6,23,3,2184,2)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (32,6,4,1,724,3)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (32,9,13,4,980,2)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (19,3,10,1,176,2)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (43,8,22,3,2424,2)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (27,9,15,3,1920,2)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (55,10,12,2,404,3)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (100,10,15,5,3200,1)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (72,2,17,3,1518,3)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (26,2,19,3,1716,3)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (18,5,19,2,1144,2)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (73,10,6,4,3576,2)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (12,9,22,2,1616,3)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (100,7,24,5,4165,2)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (4,4,20,3,2748,3)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (18,7,28,2,1722,1)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (2,5,3,1,566,1)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (84,10,19,3,1716,1)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (61,10,6,1,894,3)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (80,5,10,5,880,2)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (30,3,13,5,1225,2)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (85,1,4,5,3620,1)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (75,7,16,1,11,2)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (81,4,23,4,2912,2)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (95,6,7,3,48,3)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (15,2,12,4,808,1)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (56,10,1,1,410,2)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (26,8,10,1,176,1)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (49,10,21,3,372,3)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (100,7,18,5,4500,1)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (77,9,17,1,506,3)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (20,4,16,1,11,3)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (11,10,18,4,3600,2)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (72,7,1,1,410,3)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (60,1,30,2,208,1)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (72,4,3,1,566,3)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (16,2,16,2,22,1)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (74,7,25,1,340,3)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (99,2,29,3,981,1)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (59,9,19,2,1144,2)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (54,5,4,1,724,2)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (20,8,18,1,900,3)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (68,3,17,5,2530,3)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (70,6,25,5,1700,3)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (5,2,8,4,1988,1)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (80,1,12,4,808,3)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (53,5,8,2,994,2)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (66,5,23,2,1456,3)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (68,8,13,1,245,1)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (100,5,23,2,1456,2)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (99,9,5,1,282,1)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (12,1,9,4,3308,3)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (45,6,6,2,1788,2)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (75,6,8,4,1988,2)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (69,4,7,5,80,2)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (73,9,20,1,916,1)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (40,9,14,2,1402,1)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (17,7,9,4,3308,2)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (51,10,30,4,416,3)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (83,8,23,2,1456,2)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (61,2,9,4,3308,3)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (5,10,10,2,352,1)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (69,9,10,3,528,1)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (19,9,27,5,2365,1)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (52,2,28,5,4305,1)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (10,1,19,1,572,1)